### PR TITLE
Prevent Downloading from GCS from crashing VS.

### LINKED ISSUE #878: Downloading a file from GCS crashes VS
Extension Version 1.2.10.0
Using VS 2017

### PR DESCRIPTION
**Pull request by ILMTitan**
Fix a property that had a default two way binding, but a private setter.
Fixes #878.

### CODE REVIEW

File: GoogleCloudExtension/GoogleCloudExtensionUnitTests/GcsFileProgressDialog/GcsFileProgressDialogWindowTest.cs [hunk 1]
```diff
@@ -0,0 +1,56 @@
+﻿using GoogleCloudExtension.GcsFileProgressDialog;
```
Comment (ivannaranjo) [inline GoogleCloudExtension/GoogleCloudExtensionUnitTests/GcsFileProgressDialog/GcsFileProgressDialogWindowTest.cs]: Missing license header.

**Comment by ivannaranjo** [comment]
LGTM, thank you as always for adding more tests.
