### PR TITLE
Do not crash when there are multiple credentials files for a single user account.

### LINKED ISSUE #1065: Duplicate account files should not crash the extension.
See #1064.

Multiple user account json files with the same account name should not prevent the extension from launching. We should instead choose one arbitrarily, and delete the others.

### PR DESCRIPTION
**Pull request by ILMTitan**
Fixes #1065

### CODE REVIEW

File: GoogleCloudExtension/GoogleCloudExtension/Accounts/CredentialsStore.cs [hunk 1]
```diff
@@ -247,10 +246,19 @@ private string GetUserAccountPath(string accountName)
...
+                .Select(
+                    path => new StoredUserAccount
+                    {
+                        FileName = Path.GetFileName(path),
+                        UserAccount = LoadUserAccount(path)
+                    })
+                .GroupBy(a => a.UserAccount.AccountName)
+                .ToDictionary(
+                    g => g.Key,
+                    g => g.OrderBy(account => account.FileName, StringComparer.InvariantCulture).First());
```
Comment (quoctruong) [inline GoogleCloudExtension/GoogleCloudExtension/Accounts/CredentialsStore.cs]: nit: I think using an `Aggregate` or `Max` may be more efficient than sorting the list and get the first item.
