### PR TITLE
Fix a potential null reference exception.

### LINKED ISSUE #1057: Fix PickProject dialog null reference exceptions.

### PR DESCRIPTION
**Pull request by ILMTitan**
Fixes #1057

### CODE REVIEW

File: GoogleCloudExtension/GoogleCloudExtension/PickProjectDialog/PickProjectIdViewModel.cs [hunk 1]
```diff
@@ -134,7 +134,7 @@ public bool FilterItem(object item)
                 }
 
                 // Check name and project id for the filter.
-                return project.ProjectId.Contains(Filter) || project.Name.Contains(Filter);
+                return project.ProjectId?.Contains(Filter) == true || project.Name?.Contains(Filter) == true;
```
Comment (quoctruong) [inline GoogleCloudExtension/GoogleCloudExtension/PickProjectDialog/PickProjectIdViewModel.cs]: Does `return project.ProjectId?.Contains(Filter) || project.Name?.Containers(Filter)` work here?

Comment (quoctruong) [reply GoogleCloudExtension/GoogleCloudExtension/PickProjectDialog/PickProjectIdViewModel.cs]: If not, I think another option is `project.ProjectId?.Contains(Filter) ?? project.Name?.Contains(Filter) ?? false`

Comment (ILMTitan) [reply GoogleCloudExtension/GoogleCloudExtension/PickProjectDialog/PickProjectIdViewModel.cs]: No. Null is not a valid parameter to `||`, and the second would only check against project.Name if project.Id is null.

The other option that will work is `project.ProjectId != null && project.ProjectId.Contains(Filter) || project.Name != null && project.Name.Contains(Filter)`, but I think how I already have it looks better.

Comment (simonz130) [reply GoogleCloudExtension/GoogleCloudExtension/PickProjectDialog/PickProjectIdViewModel.cs]: I actually prefer this: 
```
project.ProjectId != null && project.ProjectId.Contains(Filter) || project.Name != null && project.Name.Contains(Filter)
```
because it's clearer what happens here to everyone who will look at it - even though ? is perfectly valid C# operator.

File: GoogleCloudExtension/GoogleCloudExtensionUnitTests/PickProjectDialog/PickProjectIdViewModelTests.cs [hunk 2]
```diff
@@ -282,5 +282,15 @@ public void TestFilterItem_ReturnsTrueForFilterMatchingId()
 
             Assert.IsTrue(result);
         }
+
+        [TestMethod]
+        public void TestFilterItem_ReturnsFalseForUninitalizedProject()
```
Comment (simonz130) [inline GoogleCloudExtension/GoogleCloudExtensionUnitTests/PickProjectDialog/PickProjectIdViewModelTests.cs]: Unititialized

File: GoogleCloudExtension/GoogleCloudExtension/PickProjectDialog/PickProjectIdViewModel.cs (hunk 1 above)
Comment (ILMTitan) [reply GoogleCloudExtension/GoogleCloudExtension/PickProjectDialog/PickProjectIdViewModel.cs]: Done.

File: GoogleCloudExtension/GoogleCloudExtensionUnitTests/PickProjectDialog/PickProjectIdViewModelTests.cs (hunk 2 above)
Comment (ILMTitan) [reply GoogleCloudExtension/GoogleCloudExtensionUnitTests/PickProjectDialog/PickProjectIdViewModelTests.cs]: Uninitialized.
Done.

**Comment by ILMTitan** [comment]
PTAL
